name: Maelstrom-Rust image

on:
  push:
    paths:
      - 'Maelstrom.docker'

env:
  REGISTRY: registry.lol3r.com
  IMAGE_NAME: maelstrom-rust

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # set latest tag for master branch
            type=raw,value=docs-latest
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Maelstrom.docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
